// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBOTUQ97yWj1L5PT8n61cWREduycTzHYA',
    appId: '1:443636485902:web:e34abf0577c97b17f5915f',
    messagingSenderId: '443636485902',
    projectId: 'temu-wisata',
    authDomain: 'temu-wisata.firebaseapp.com',
    storageBucket: 'temu-wisata.firebasestorage.app',
    measurementId: 'G-NJKXCT5X6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Zhpidynlq1SGUmmOoyQ61lAQhrZ_s4U',
    appId: '1:443636485902:android:d75ed0f3d2a6bf5bf5915f',
    messagingSenderId: '443636485902',
    projectId: 'temu-wisata',
    storageBucket: 'temu-wisata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXxSjOudPn4QCICa950g8uC8Bjp1_L1E',
    appId: '1:443636485902:ios:5f575e26d9edd646f5915f',
    messagingSenderId: '443636485902',
    projectId: 'temu-wisata',
    storageBucket: 'temu-wisata.firebasestorage.app',
    iosBundleId: 'com.example.mdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXxSjOudPn4QCICa950g8uC8Bjp1_L1E',
    appId: '1:443636485902:ios:5f575e26d9edd646f5915f',
    messagingSenderId: '443636485902',
    projectId: 'temu-wisata',
    storageBucket: 'temu-wisata.firebasestorage.app',
    iosBundleId: 'com.example.mdi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBOTUQ97yWj1L5PT8n61cWREduycTzHYA',
    appId: '1:443636485902:web:f86dc1480d58b047f5915f',
    messagingSenderId: '443636485902',
    projectId: 'temu-wisata',
    authDomain: 'temu-wisata.firebaseapp.com',
    storageBucket: 'temu-wisata.firebasestorage.app',
    measurementId: 'G-47VVZK89HM',
  );
}
